### ISSUE TITLE
RockDB fails to start when running Grakn

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/grakn#4651] opened 2018-11-26 11:32 UTC
Error message: 

Process exited with code '0': 'Uncaught exception at thread [org.rocksdb.RocksDBException: While lock file: /private/var/tmp/_bazel_syedirtazaraza/90ccd6849586c30538214c7f5552cb85/execroot/grakn_core/bazel-out/darwin-fastbuild/genfiles/dist/grakn-core-all/db/queue/LOCK: Resource temporarily unavailable]

**Comment by Irtazaraza** [comment] 2018-11-26 11:35
jps shows Grakn running however ./grakn server status shows Grakn is not running

**Comment by lolski** [comment] 2018-12-20 19:40
This issue is caused by the fact that you've already another Grakn running in the background. Closing.

**Closed by lolski** 2018-12-20 19:40 UTC
Labels: bug, v1.5
