### ISSUE TITLE
When session is closed outside of shell, the shell should refresh the session or die completely.

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3087] opened 2018-09-21 18:04 UTC
_This issue was originally posted by @haikalpribadi  on 2017-05-15 18:34_.

**Comment by marco-scoppetta** [comment] 2019-02-28 10:42
Just verified this behaviour and the one described in https://work.grakn.ai/entity/18517-incorrect-transaction-shutdown-in-graql-shell. The issue is resolved in Grakn 1.5 in `master`, the 2 sessions are independent and don't interfere with each other.

**Closed by marco-scoppetta** 2019-02-28 10:42 UTC
Labels: feature
