### ISSUE TITLE
Random failure in `GetQueryPropertyTest`

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3820] opened 2018-09-21 23:48 UTC
_This issue was originally posted by @haikalpribadi  on 2018-01-05 15:48_.

```
 Failed tests: ai.grakn.test.property.graql.GetQueryPropertyTest.varPatternIsAMorphism_From_VarPropertiesWithUnion_To_PatternsWithConjunction(ai.grakn.test.property.graql.GetQueryPropertyTest) Run 1: GetQueryPropertyTest.varPatternIsAMorphism_From_VarPropertiesWithUnion_To_PatternsWithConjunction Unexpected error in property varPatternIsAMorphism_From_VarPropertiesWithUnion_To_PatternsWithConjunction with args [ai.grakn.kb.internal.GraknTxTinker@30ae6721, $foo, [isa relationship], [datatype double, isa `$quux (thud: `$garply isa `$quux is-abstract``, quux: $grault, $foo)`]] and seeds [1373342910996112379, -5362347430936678247, -3955990934625955716, -7664614208227394797] Run 2: GetQueryPropertyTest.varPatternIsAMorphism_From_VarPropertiesWithUnion_To_PatternsWithConjunction Unexpected error in property varPatternIsAMorphism_From_VarPropertiesWithUnion_To_PatternsWithConjunction with args [ai.grakn.kb.internal.GraknTxTinker@15a242e2, $bar, [], [isa attribute, isa `$thud (thud: $baz)`]] and seeds [-469572963741889224, -8103198193585450717, -2530153031216599128, 1386472902156641988] 
```

**Comment by marco-scoppetta** [comment] 2019-02-26 13:47
closing as it's duplicate of https://github.com/graknlabs/grakn/issues/3161

**Closed by marco-scoppetta** 2019-02-26 13:47 UTC
Labels: bug
