### ISSUE TITLE
Introduce MultiAnswer state for permuted answers

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3797] opened 2018-09-21 23:46 UTC
_This issue was originally posted by @kasper-piskorski  on 2017-10-02 11:15_.

For cases when we have multiple answers being permutations of each other it might be beneficial to introduce a MultiAnswer state dealing with the permutations instead of progressing in the standard way.

**Comment by kasper-piskorski** [comment] 2019-07-08 17:43
duplicate of #4549

**Closed** 2019-07-08 17:43 UTC
Labels: duplicate, feature
