### ISSUE TITLE
Graql negation acts a bit funny

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#6034] opened 2021-01-15 03:41 UTC
## Description

I'm not sure if this is a bug but it is at least behavior that is different from Grakn 1.x and I don't remember reading something which indicated it would work this way. 

## Environment

1. OS (where Grakn server runs): Ubuntu 20
2. Grakn version (and platform): Grakn 2.0.0-alpha
3. Grakn client: console

### Schema
```
define
email sub entity,
    plays sent_email:is_sent,
    plays open_email:is_open;
open_email sub relation,
    relates is_open;
sent_email sub relation,
    relates is_sent;
```

### Data
```
insert $e1 isa email; ($e1) isa sent_email; ($e1) isa open_email; $e2 isa email; ($e2) isa sent_email;
```

### Given the above schema and data

This query returns nothing:
```
match $e isa email; ($e) isa sent_email; not { $r ($e) isa open_email; };
```

While this query returns the correct result:
```
match $e isa email; ($e) isa sent_email; $r isa open_email; not { $r ($e); };
```

## Expected Output

I would expect both queries to return the one matching result.

## Actual Output

Only the second query returns the one matching result.

**Comment by thomaschristopherking** [comment] 2021-01-21 19:12
I have also run into this issue but with negation of attributes. Luckily I found this bug report right after posting my question on StackOverflow, where there is an example: https://stackoverflow.com/questions/65833692/how-do-i-find-grakn-2-0-entities-that-lack-an-attribute-of-a-specific-type/65834229#65834229

**Comment by VladGan** [comment] 2021-01-22 09:47
@BFergerson are you sure you didn't forget to `close` write transaction? 
I was not able to reproduce your example in a 'normal' situation, but I did saw a similar issue when I queried data withouth committing it.

@thomaschristopherking
I replied to you on StackOverflow. 
Can you provide some reproducible example so I can check it? Also, please verify if you committed the write transaction before querying the data.

**Comment by BFergerson** [comment] 2021-01-22 16:33
I've confirmed this issue is fixed as of Grakn Core 2.0.0-alpha-2. I re-ran this issue against Grakn Core 2.0.0-alpha and confirmed the way I've described the issue above is accurate. The issue persists despite properly closing the write transaction, etc.

**Comment by BFergerson** [comment] 2021-01-22 17:49
@VladGan , I can't reproduce the original issue with negation but there is still something funny happening with negation.

Using the following code:
```groovy
def graknHost = "localhost"
def graknPort = 1729
def graknKeyspace = "grakn"
def graknClient = new GraknClient(graknHost + ":" + graknPort)
if (graknClient.databases().contains(graknKeyspace)) graknClient.databases().delete(graknKeyspace)
graknClient.databases().create(graknKeyspace)
def schemaSession = graknClient.session(graknKeyspace, Grakn.Session.Type.SCHEMA)

//save schema
def tx = schemaSession.transaction(Grakn.Transaction.Type.WRITE)
tx.query().define(Graql.parseQuery(
        """
define

JavaSourceArtifact sub entity;
JavaMethodDeclarationArtifact sub JavaSourceArtifact,
    plays DECLARATION:IS_DECLARATION,
    plays FUNCTION:IS_FUNCTION;
JavaSimpleNameArtifact sub JavaSourceArtifact,
    plays ARGUMENT:IS_ARGUMENT,
    plays FUNCTION:IS_FUNCTION;

ARGUMENT sub relation,
    relates IS_ARGUMENT;
DECLARATION sub relation,
    relates IS_DECLARATION;
FUNCTION sub relation,
    relates IS_FUNCTION;
"""
) as GraqlDefine)
tx.commit()
tx.close()
schemaSession.close()

def dataSession = graknClient.session(graknKeyspace, Grakn.Session.Type.DATA)

def writeTx = dataSession.transaction(Grakn.Transaction.Type.WRITE)
writeTx.query().insert(Graql.parseQuery("""
insert
    \$f isa JavaMethodDeclarationArtifact; (IS_FUNCTION: \$f) isa FUNCTION; (IS_DECLARATION: \$f) isa DECLARATION;
    \$s isa JavaSimpleNameArtifact; (IS_ARGUMENT: \$s) isa ARGUMENT;
"""))
writeTx.commit()
writeTx.close()

try (def readTx = dataSession.transaction(Grakn.Transaction.Type.READ)) {
    println readTx.query().match(Graql.parseQuery("""
match \$f isa JavaSourceArtifact; (\$f) isa DECLARATION; (\$f) isa FUNCTION; not { (\$f) isa ARGUMENT; };
""")).collect()
}

dataSession.close()
graknClient.close()
```

I am able to trigger the error:

### Client
```
2021-01-22 17:48:21,091 [ForkJoinPool-1-worker-55] [ERROR] grakn.core.rocks.RocksStorage - grakn.core.common.exception.GraknException: [QRY14] Invalid Query Pattern: The conjunction ($f), isa ARGUMENT;
$f , iid 0x966e80018000000000000000; can never be satisfied within the current schema.
grakn.core.common.exception.GraknException: grakn.core.common.exception.GraknException: [QRY14] Invalid Query Pattern: The conjunction ($f), isa ARGUMENT;
$f , iid 0x966e80018000000000000000; can never be satisfied within the current schema.
at grakn.core.common.exception.GraknException.of(GraknException.java:51)
at grakn.core.common.producer.ProducerIterator.hasNext(ProducerIterator.java:93)
at grakn.core.common.iterator.ErrorHandledIterator.hasNext(ErrorHandledIterator.java:38)
at grakn.core.server.rpc.TransactionRPC$Iterators$BatchingIterator.iterateBatch(TransactionRPC.java:234)
at grakn.core.server.rpc.TransactionRPC$Iterators.beginIteration(TransactionRPC.java:202)
at grakn.core.server.rpc.TransactionRPC.respond(TransactionRPC.java:137)
at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:95)
at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:68)
at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: grakn.core.common.exception.GraknException: [QRY14] Invalid Query Pattern: The conjunction ($f), isa ARGUMENT;
$f , iid 0x966e80018000000000000000; can never be satisfied within the current schema.
at grakn.core.common.exception.GraknException.of(GraknException.java:55)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:99)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:85)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:115)
at grakn.core.reasoner.Reasoner.lambda$producers$6(Reasoner.java:111)
at grakn.core.common.iterator.FlatMappedIterator.initialiseAndSetState(FlatMappedIterator.java:62)
at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:44)
at grakn.common.collection.Either.apply(Either.java:71)
at grakn.core.common.iterator.BaseIterator.hasNext(BaseIterator.java:35)
at grakn.core.common.iterator.FlatMappedIterator.fetchAndCheck(FlatMappedIterator.java:52)
at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:48)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
at grakn.core.common.iterator.AbstractResourceIterator.toList(AbstractResourceIterator.java:136)
at grakn.core.reasoner.Reasoner.lambda$producers$4(Reasoner.java:106)
at grakn.core.common.producer.FilteredProducer$Queue.put(FilteredProducer.java:56)
at grakn.core.common.producer.MappedProducer$Queue.put(MappedProducer.java:56)
at grakn.core.traversal.producer.GraphProducer.job(GraphProducer.java:127)
at grakn.core.traversal.producer.GraphProducer.lambda$distribute$0(GraphProducer.java:95)
at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
... 5 common frames omitted
2021-01-22 17:48:21,093 [ForkJoinPool-1-worker-55] [ERROR] g.core.server.rpc.TransactionStream - grakn.core.common.exception.GraknException: [QRY14] Invalid Query Pattern: The conjunction ($f), isa ARGUMENT;
$f , iid 0x966e80018000000000000000; can never be satisfied within the current schema.
grakn.core.common.exception.GraknException: grakn.core.common.exception.GraknException: [QRY14] Invalid Query Pattern: The conjunction ($f), isa ARGUMENT;
$f , iid 0x966e80018000000000000000; can never be satisfied within the current schema.
at grakn.core.common.exception.GraknException.of(GraknException.java:51)
at grakn.core.common.producer.ProducerIterator.hasNext(ProducerIterator.java:93)
at grakn.core.common.iterator.ErrorHandledIterator.hasNext(ErrorHandledIterator.java:38)
at grakn.core.server.rpc.TransactionRPC$Iterators$BatchingIterator.iterateBatch(TransactionRPC.java:234)
at grakn.core.server.rpc.TransactionRPC$Iterators.beginIteration(TransactionRPC.java:202)
at grakn.core.server.rpc.TransactionRPC.respond(TransactionRPC.java:137)
at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:95)
at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:68)
at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: grakn.core.common.exception.GraknException: [QRY14] Invalid Query Pattern: The conjunction ($f), isa ARGUMENT;
$f , iid 0x966e80018000000000000000; can never be satisfied within the current schema.
at grakn.core.common.exception.GraknException.of(GraknException.java:55)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:99)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:85)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:115)
at grakn.core.reasoner.Reasoner.lambda$producers$6(Reasoner.java:111)
at grakn.core.common.iterator.FlatMappedIterator.initialiseAndSetState(FlatMappedIterator.java:62)
at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:44)
at grakn.common.collection.Either.apply(Either.java:71)
at grakn.core.common.iterator.BaseIterator.hasNext(BaseIterator.java:35)
at grakn.core.common.iterator.FlatMappedIterator.fetchAndCheck(FlatMappedIterator.java:52)
at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:48)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
at grakn.core.common.iterator.AbstractResourceIterator.toList(AbstractResourceIterator.java:136)
at grakn.core.reasoner.Reasoner.lambda$producers$4(Reasoner.java:106)
at grakn.core.common.producer.FilteredProducer$Queue.put(FilteredProducer.java:56)
at grakn.core.common.producer.MappedProducer$Queue.put(MappedProducer.java:56)
at grakn.core.traversal.producer.GraphProducer.job(GraphProducer.java:127)
at grakn.core.traversal.producer.GraphProducer.lambda$distribute$0(GraphProducer.java:95)
at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
... 5 common frames omitted
```

---

There seems to be some logic which reports that something is invalid when it just means to say that it didn't find any solutions due to constraints the schema/data has. 

In my above example:
 - I define a schema with `JavaMethodDeclarationArtifact` and `JavaSimpleNameArtifact`
 - I insert data
    - `$f` isa `JavaMethodDeclarationArtifact` with connections `FUNCTION` and `DECLARATION`
    - `$s` isa `JavaSimpleNameArtifact` with a connection `ARGUMENT`
 - I run a query looking for any answers which have `FUNCTION` and `DECLARATION` but not `ARGUMENT`

Everything works correctly until the negation is introduced. The previous trick I used in the original issue no longer works.

**Comment by BFergerson** [comment] 2021-01-30 00:22
The issue is still present as of client 2.0.0-alpha-7 and server 2.0.0-alpha-4. I've converted the reproduction code to Java:
```java
import grakn.client.GraknClient;
import graql.lang.query.GraqlMatch;

import java.util.stream.Collectors;

import static graql.lang.Graql.parseQuery;

public class TestIssue {
    public static void main(String[] args) {
        //connect to grakn
        var graknHost = "localhost";
        var graknPort = 1729;
        var graknKeyspace = "grakn";
        var graknClient = GraknClient.core(graknHost + ":" + graknPort);
        if (graknClient.databases().contains(graknKeyspace)) graknClient.databases().delete(graknKeyspace);
        graknClient.databases().create(graknKeyspace);
        var schemaSession = graknClient.session(graknKeyspace, GraknClient.Session.Type.SCHEMA);

        //save schema
        var tx = schemaSession.transaction(GraknClient.Transaction.Type.WRITE);
        tx.query().define(parseQuery("define\n" +
                "JavaSourceArtifact sub entity;\n" +
                "JavaMethodDeclarationArtifact sub JavaSourceArtifact,\n" +
                "    plays DECLARATION:IS_DECLARATION,\n" +
                "    plays FUNCTION:IS_FUNCTION;\n" +
                "JavaSimpleNameArtifact sub JavaSourceArtifact,\n" +
                "    plays ARGUMENT:IS_ARGUMENT,\n" +
                "    plays FUNCTION:IS_FUNCTION;\n" +
                "\n" +
                "ARGUMENT sub relation,\n" +
                "    relates IS_ARGUMENT;\n" +
                "DECLARATION sub relation,\n" +
                "    relates IS_DECLARATION;\n" +
                "FUNCTION sub relation,\n" +
                "    relates IS_FUNCTION;"));
        tx.commit();
        tx.close();
        schemaSession.close();

        var dataSession = graknClient.session(graknKeyspace, GraknClient.Session.Type.DATA);

        //write data
        var writeTx = dataSession.transaction(GraknClient.Transaction.Type.WRITE);
        writeTx.query().insert(parseQuery("insert\n" +
                "    $f isa JavaMethodDeclarationArtifact; (IS_FUNCTION: $f) isa FUNCTION; (IS_DECLARATION: $f) isa DECLARATION;\n" +
                "    $s isa JavaSimpleNameArtifact; (IS_ARGUMENT: $s) isa ARGUMENT;"));
        writeTx.commit();
        writeTx.close();

        //read data
        try (var readTx = dataSession.transaction(GraknClient.Transaction.Type.READ)) {
            System.out.println(readTx.query().match((GraqlMatch) parseQuery(
                    "match $f isa JavaSourceArtifact; ($f) isa DECLARATION; ($f) isa FUNCTION; not { ($f) isa ARGUMENT; };"))
                    .collect(Collectors.toList()));
        }

        //clean up
        dataSession.close();
        graknClient.close();
    }
}
```

**Comment by BFergerson** [comment] 2021-01-30 01:14
A more conceptually simple example:
```java
import grakn.client.GraknClient;
import graql.lang.query.GraqlMatch;

import java.util.stream.Collectors;

import static graql.lang.Graql.parseQuery;

public class TestIssue {
    public static void main(String[] args) {
        //connect to grakn
        var graknHost = "localhost";
        var graknPort = 1729;
        var graknKeyspace = "grakn";
        var graknClient = GraknClient.core(graknHost + ":" + graknPort);
        if (graknClient.databases().contains(graknKeyspace)) graknClient.databases().delete(graknKeyspace);
        graknClient.databases().create(graknKeyspace);
        var schemaSession = graknClient.session(graknKeyspace, GraknClient.Session.Type.SCHEMA);

        //save schema
        var tx = schemaSession.transaction(GraknClient.Transaction.Type.WRITE);
        tx.query().define(parseQuery("define\n" +
                "animal sub entity;\n" +
                "bird sub animal, plays FLYS:IS_FLYS, plays WALKS:IS_WALKS;\n" +
                "dog sub animal, plays WALKS:IS_WALKS;\n" +
                "\n" +
                "FLYS sub relation,\n" +
                "    relates IS_FLYS;\n" +
                "WALKS sub relation,\n" +
                "    relates IS_WALKS;"));
        tx.commit();
        tx.close();
        schemaSession.close();

        var dataSession = graknClient.session(graknKeyspace, GraknClient.Session.Type.DATA);

        //write data
        var writeTx = dataSession.transaction(GraknClient.Transaction.Type.WRITE);
        writeTx.query().insert(parseQuery("insert $b isa bird; ($b) isa FLYS; ($b) isa WALKS;\n" +
                "   $d isa dog; ($d) isa WALKS;"));
        writeTx.commit();
        writeTx.close();

        //read data
        try (var readTx = dataSession.transaction(GraknClient.Transaction.Type.READ)) {
            System.out.println(readTx.query().match((GraqlMatch) parseQuery(
                    "match $a isa animal; ($a) isa WALKS; not { ($a) isa FLYS; };\n"))
                    .collect(Collectors.toList()));
        }

        //clean up
        dataSession.close();
        graknClient.close();
    }
}
```

**Comment by haikalpribadi** [comment] 2021-01-30 02:04
Okay, I understand what the underlying issue is here now. I'll push a fix ASAP this weekend.

**Comment by haikalpribadi** [comment] 2021-01-30 19:47
I've reproduced and fixed the above scenario in this commit, @BFergerson : https://github.com/graknlabs/grakn/commit/5c94e3c2d4190f5686130091a6f930add40b5ca5

Would you mind testing the distribution straight off `master`? You just need to run either one of the following commands from a cloned Grakn repo:
-  `bazel build //:assemble-linux-targz` (Outputs to: `bazel-bin/grakn-core-all-linux.tar.gz`)
- `bazel build //:assemble-mac-zip` (Outputs to: `bazel-bin/grakn-core-all-mac.zip`)
- `bazel build //:assemble-windows-zip` (Outputs to: `bazel-bin/grakn-core-all-windows.zip`)

**Closed by haikalpribadi** 2021-01-30 19:47 UTC
Labels: priority: blocker, type: bug

**Comment by BFergerson** [comment] 2021-01-30 21:09
@haikalpribadi, running the above command results in `graql.lang.common.exception.GraqlException: [GQL04] Graql Error: The class 'GraqlDefine' cannot be casted to 'GraqlUndefine'`. Seems the protocol message-ids have been changed and the dependencies haven't yet been updated to reflect that.

It seems a bit odd for message-ids to changes. Won't the previous 2.0.0-alpha client not work with the next alpha release?

**Comment by haikalpribadi** [comment] 2021-01-31 00:03
Ah, yes, the client protocol changed after the alpha-4 release @BFergerson ! Can you depend on the latest client-java at commit https://github.com/graknlabs/client-java/commit/0a971ec467d3736d38908ac29aa57ec2316f16c0 ? You can set the maven version to the commit sha `0a971ec467d3736d38908ac29aa57ec2316f16c0`

**Comment by BFergerson** [comment] 2021-01-31 01:14
Verified negation issue resolved using latest client-java and core.
