### ISSUE TITLE
Roleplayers of a single role are not enforced to be distinct

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5658] opened 2020-03-17 11:29 UTC
## Description

It is currently possible to write patterns where either explicitly or implicitly there is a duplicate definition for a (role, roleplayer) tuple in a relation, and they can be executed as if they are valid.

Related to #5649

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
```
case1> match $x sub thing; get;
{$x type thing;}
{$x type relation;}
{$x type entity;}
{$x type attribute;}
case1> define person sub entity, plays friend; friendship sub relation, relates friend;
{}
case1> commit
case1> insert $x isa person;
{$x id V8200 isa person;}
case1> commit
case1> match $x isa person; insert $f(friend: $x, friend: $x) isa friendship;
{$f id V12352 (friend: id V8200) isa friendship; $x id V8200 isa person;}
case1> commit
case1> match $x isa person; $y isa person; insert $f(friend: $x, friend: $y) isa friendship;
{$f id V8320 (friend: id V8200) isa friendship; $x id V8200 isa person; $y id V8200 isa person;}
case1> commit
case1> match (friend: $f1, friend: $f2) isa friendship; get;
case1> match $f(friend: $x, friend: $x) isa friendship; get;
case1> match $f(friend: $x) isa friendship; get;
{$f id V8320 (friend: id V8200) isa friendship; $x id V8200 isa person;}
{$f id V12352 (friend: id V8200) isa friendship; $x id V8200 isa person;}
case1> match $f(friend: $x) isa friendship; $f(friend: $x) isa friendship; get;
{$f id V8320 (friend: id V8200) isa friendship; $x id V8200 isa person;}
{$f id V12352 (friend: id V8200) isa friendship; $x id V8200 isa person;}
case1>
```

## Expected Output vs. Desired Output
From discussion with @haikalpribadi and @flyingsilverfin, we think that:
- `match $x isa person; insert $f(friend: $x, friend: $x) isa friendship;` should throw an error, ideally at parse-time.

- `match $x isa person; $y isa person; insert $f(friend: $x, friend: $y) isa friendship;` should throw an error at runtime, once it has been established that `$x` and `$y` are equivalent.

- `match (friend: $f1, friend: $f2) isa friendship; get;` is currently correct in returning no results here

- `match $f(friend: $x, friend: $x) isa friendship; get;` should throw an error at parse-time

**Comment by flyingsilverfin** [comment] 2020-04-08 18:02
@jmsfltchr  is this now solved then?

**Comment by haikalpribadi** [comment] 2020-04-08 18:05
If you can't reproduce the bug now after the new PRs have went in, then yes you should close this and label it `solved` @flyingsilverfin

**Comment by jmsfltchr** [comment] 2020-04-09 13:11
@flyingsilverfin yes this is solved in that we have made the design decision to change the behaviour from `put` to `add` for roleplayers, which invalidates this issue

**Closed** 2020-04-09 13:12 UTC
Labels: status: invalid, type: bug

**Comment by haikalpribadi** [comment] 2020-04-09 14:10
why is it invalid, @jmsfltchr ? We actually solved the problem by changing the behaviour of the operation. I think this should be labelled `solved` now.

**Comment by haikalpribadi** [comment] 2020-04-09 14:16
FYI, `invalid` should only be used if the issue was not a valid issue, in the sense that it was mistakenly thought to be a bug, or an issue that was relevant to the repository, @jmsfltchr
