### ISSUE TITLE
Query cache contains invalid entry

### ISSUE THREAD

**Issue by tapple** [graknlabs/grakn#5045] opened 2019-03-19 00:07 UTC
I ran this query, and, after about an hour, it threw an exception. I'm running 1.4.2. I'm guessing this might be fixed in 1.5
```
>>> match $x isa relationship; aggregate count;
UNKNOWN: ai.grakn.exception.GraqlQueryException: Query cache entry for query [$1552600009398917 in_flow[callee: $b, caller: $a][$b/V721088]] contains invalid entry.. Please check server logs for the stack trace.

```
```
97248 2019-03-18 18:54:00,600 [grpc-default-executor-59] ERROR a.g.e.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:
97249 java.lang.RuntimeException: ai.grakn.exception.GraqlQueryException: Query cache entry for query [$1552600009332996 in_flow[callee: $b, caller: $a][$b/V438504]] contains invalid entry.
97250         at ai.grakn.engine.rpc.SessionService$TransactionListener.submit(SessionService.java:202)
97251         at ai.grakn.engine.rpc.SessionService$TransactionListener.onNext(SessionService.java:115)
97252         at ai.grakn.engine.rpc.SessionService$TransactionListener.onNext(SessionService.java:79)
97253         at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248)
97254         at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
97255         at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683)
97256         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
97257         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
97258         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
97259         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
97260         at java.lang.Thread.run(Thread.java:748)
97261 Caused by: ai.grakn.exception.GraqlQueryException: Query cache entry for query [$1552600009332996 in_flow[callee: $b, caller: $a][$b/V438504]] contains invalid entry.
97262         at ai.grakn.exception.GraqlQueryException.invalidQueryCacheEntry(GraqlQueryException.java:322)
97263         at ai.grakn.graql.internal.reasoner.cache.SimpleQueryCache.lambda$record$0(SimpleQueryCache.java:112)
97264         at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
97265         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
97266         at java.util.Iterator.forEachRemaining(Iterator.java:116)
97267         at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
97268         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
97269         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
97270         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
97271         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
97272         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
97273         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
97274         at ai.grakn.graql.internal.reasoner.cache.SimpleQueryCache.record(SimpleQueryCache.java:115)
97275         at ai.grakn.graql.internal.reasoner.state.AtomicState.consumeAnswer(AtomicState.java:88)
97276         at ai.grakn.graql.internal.reasoner.state.AnswerState.getAnswer(AnswerState.java:61)
97277         at ai.grakn.graql.internal.reasoner.state.AtomicState.propagateAnswer(AtomicState.java:63)
97278         at ai.grakn.graql.internal.reasoner.state.AnswerState.generateSubGoal(AnswerState.java:54)
97279         at ai.grakn.graql.internal.reasoner.ResolutionIterator.findNextAnswer(ResolutionIterator.java:76)
97280         at ai.grakn.graql.internal.reasoner.ResolutionIterator.hasNext(ResolutionIterator.java:100)
97281         at java.util.Iterator.forEachRemaining(Iterator.java:115)
97282         at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
97283         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
97284         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
97285         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
97286         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
97287         at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
97288         at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
97289         at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
97290         at ai.grakn.graql.internal.query.aggregate.CountAggregate.apply(CountAggregate.java:46)
97291         at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.run(QueryExecutorImpl.java:136)
97292         at ai.grakn.graql.internal.query.AggregateQueryImpl.stream(AggregateQueryImpl.java:48)
97293         at ai.grakn.engine.rpc.SessionService$TransactionListener.query(SessionService.java:229)
97294         at ai.grakn.engine.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:140)
97295         at ai.grakn.engine.rpc.SessionService$TransactionListener.lambda$onNext$0(SessionService.java:115)
97296         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
97297         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
97298         ... 3 common frames omitted
```

**Comment by marco-scoppetta** [comment] 2019-04-02 14:02
@tapple are you able to provide any more details on this? data or schema? have you had a chance to try the same scenario with Grakn 1.5?

**Comment by marco-scoppetta** [comment] 2019-05-01 12:12
@tapple I am going to close this issue as without other details we were not able to reproduce it and since this issue we have reworked caching, so please open a new issue if this happens again.

**Closed by marco-scoppetta** 2019-05-01 12:12 UTC
Labels: bug
