### ISSUE TITLE
Possible creation of duplicate edges via rules

### ISSUE THREAD

**Issue by kasper-piskorski** [graknlabs/grakn#5600] opened 2020-02-27 17:07 UTC
## Description

It seems possible to create scenarios in which querying for a duplicate edge returns results, i. e. querying for:

`(someRole: $x, someRole: $x)` 

would return a non-empty set of results.

## Reproducible Steps

Dataset:
```
define name sub attribute, datatype string;
define friendship sub relation, relates friend;
define person sub entity, has name, plays friend;
define friendship-transitive sub rule, 
when { 
    (friend: $f1, friend: $f2) isa friendship;
    (friend: $f2, friend: $f3) isa friendship;}
, then {  
    (friend: $f1, friend: $f3) isa friendship;
};
insert $x isa person, has name "Alice";
insert $x isa person, has name "Bob";
insert $x isa person, has name "Charlie";
match $alice isa person, has name "Alice"; $bob isa person, has name "Bob"; insert (friend:$alice,friend:$bob) isa friendship;
match $alice isa person, has name "Alice"; $charlie isa person, has name "Charlie"; insert (friend:$alice,friend:$charlie) isa friendship;
```

Query:
`match (friend: $f, friend: $f) isa friendship; get;`

## Expected Output

Empty result set.

## Actual Output
Non-empty result set.

**Comment by flyingsilverfin** [comment] 2020-03-30 09:35
Duplicate of #5649

**Closed by flyingsilverfin** 2020-03-30 09:35 UTC
Labels: type: bug
