### ISSUE TITLE
Please print the stack track of the IO exception so that we know why the imported file is not readable 

### ISSUE THREAD

**Issue by RamAnvesh** [graknlabs/grakn#6165] opened 2021-02-12 14:24 UTC
https://github.com/graknlabs/grakn/blob/a318ae40eef90c5496088139b788ebf32459d175/server/migrator/Importer.java#L110

**Comment by RamAnvesh** [comment] 2021-02-12 14:37
I am consistently facing the following issue during grakn console import
```
2021-02-12 19:55:24,286 [grakn-core-main::9] [ERROR] g.core.server.rpc.MigratorRPCService - [MIG01] Migrator failure: The specified file '/Users/ramanvesh/codebase/odin/commons/examples/loadtests/clear_db.gql' cannot be opened for read.
grakn.core.common.exception.GraknException: [MIG01] Migrator failure: The specified file '/Users/ram.anvesh/codebase/odin/commons/examples/loadtests/clear_db.gql' cannot be opened for read.
	at grakn.core.common.exception.GraknException.of(GraknException.java:55)
	at grakn.core.server.migrator.Importer.run(Importer.java:110)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)/
```

**Comment by haikalpribadi** [comment] 2021-04-13 14:26
Thanks for reporting this issue, @RamAnvesh ! Actually the problem is that the file does not actually exist at the provided path, but the error message doesn't seem to be that helpful. We've improved the error message now to make this obvious - implemented in this PR: https://github.com/graknlabs/grakn/pull/6295 .

I'll close this issue for now, but let us know if you have further troubles!

**Closed by haikalpribadi** 2021-04-13 14:26 UTC
Labels: priority: high, type: bug
