### ISSUE TITLE
Client returns different total number of entities in a non-deterministic way

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/grakn#6009] opened 2021-01-09 22:48 UTC
## Description

I am counting the number of gene entities in Grakn using Python. 

## Environment

1. OS: Mac OS 10.14
2. Grakn version: Grakn Core 2.0.0-alpha
3. Grakn client-python version: client-python 2.0.0-alpha-4
4. Python version: 3.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run this grakn distribution: https://www.dropbox.com/s/1y3ophwlv6xyg2z/grakn-2.0-alpha-tomas-20210109.zip?dl=0
2. In a terminal run python, and run: 
```
from grakn.client import GraknClient, SessionType, TransactionType
client = GraknClient("localhost:1729")
session = client.session("biograkn_covid_16", SessionType.DATA)
tx = session.transaction(TransactionType.READ)
answer_iterator = tx.query().match("match $x isa gene; get $x;")
n = 0
for answer in answer_iterator:
	n = n + 1
print("There are " + str(n) + " genes.")
tx.close()
```
4. I ran this several times and I got different counts. 
5. In the last query, I added a limit 1000 (`match $x isa gene; get $x; limit 1000;`) and then I got this error: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/transaction.py", line 136, in _fetch
    response = next(self._response_iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_channel.py", line 784, in _next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/stream.py", line 50, in __next__
    res = self._transaction._fetch(self._request_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grakn/rpc/transaction.py", line 145, in _fetch
    raise GraknClientException("The transaction has been closed and no further operation is allowed.")
grakn.common.exception.GraknClientException: The transaction has been closed and no further operation is allowed.
```

## Expected Output

I expect to be returned with +- 20,000 genes, because that's how many were inserted. 

## Actual Output

A different number every time I run the code. 
 
## Additional information

![image](https://user-images.githubusercontent.com/20223184/104110143-826e3a00-52cc-11eb-8d24-2fad4ce3eb6e.png)

**Comment by lriuui0x0** [comment] 2021-01-11 10:40
I'm reassigning from @VladGan to me, since I believe this is a graph producer problem that I'm fixing.

**Comment by lolski** [comment] 2021-01-11 11:01
Cool @lriuui0x0

**Comment by lriuui0x0** [comment] 2021-01-11 15:34
@tomassabat @lolski I have confirmed that this bug has been fixed in the latest grakn.

```
> python3 test.py                                                                                                                                                                                                                                                       1.876s
There are 20219 genes.
```

**Closed** 2021-01-11 15:35 UTC
Labels: type: bug
