### ISSUE TITLE
Unable to upgrade to newer Grakn while preserving existing data by copying the db folder

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#5147] opened 2019-05-01 16:45 UTC
## Description

If you tried to upgrade to 1.5.2 and wants to bring your old data from 1.5.1, it will cause a bug where you'll be unable to create a new keyspace.

## Environment

1. OS (where Grakn server runs): Mac
2. Grakn version (and platform): 1.5.2
3. Grakn client: N/A
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
```
$ wget https://github.com/graknlabs/grakn/releases/download/1.5.1/grakn-core-all-mac-1.5.1.zip
$ unzip grakn-core-all-mac-1.5.1.zip
$ cd grakn-core-all-mac-1.5.1
$ ./grakn server start
$ ./grakn console -k shouldwork
shouldwork> define person sub entity;
shouldwork> commit
shouldwork> CTRL+C
$ ./grakn server stop
$ cd ..
$ wget https://github.com/graknlabs/grakn/releases/download/1.5.2/grakn-core-all-mac-1.5.2.zip
$ unzip grakn-core-all-mac-1.5.2.zip
$ cd grakn-core-all-mac-1.5.2
$ rm -rf server/db
$ cp ../grakn-core-all-mac-1.5.1/server/db server/db
$ ./grakn server start
$ ./grakn console -k shouldwork
shouldwork> match $t sub thing; get;
$ ./grakn console -k shouldnotwork
io.grpc.StatusRuntimeException: UNKNOWN: null. Please check server logs for the stack trace.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at grakn.core.protocol.SessionServiceGrpc$SessionServiceBlockingStub.open(SessionServiceGrpc.java:273)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:172)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:140)
	at grakn.client.GraknClient.session(GraknClient.java:127)
	at grakn.core.console.ConsoleSession.<init>(ConsoleSession.java:86)
	at grakn.core.console.GraknConsole.run(GraknConsole.java:115)
	at grakn.core.console.GraknConsole.main(GraknConsole.java:138)
```

## Expected Output

```
$ ./grakn console -k shouldnotwork # should connect to a new keyspace 'shouldnotwork'
```

## Actual Output

```
$ ./grakn console -k shouldnotwork
io.grpc.StatusRuntimeException: UNKNOWN: null. Please check server logs for the stack trace.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at grakn.core.protocol.SessionServiceGrpc$SessionServiceBlockingStub.open(SessionServiceGrpc.java:273)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:172)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:140)
	at grakn.client.GraknClient.session(GraknClient.java:127)
	at grakn.core.console.ConsoleSession.<init>(ConsoleSession.java:86)
	at grakn.core.console.GraknConsole.run(GraknConsole.java:115)
	at grakn.core.console.GraknConsole.main(GraknConsole.java:138)
```

**Comment by lolski** [comment] 2019-05-02 10:13
I believe the internal data structure should also have a formal definition just like Graql and gRPC.

That would allow us to decide when we want to introduce a breaking change into the format.

**Comment by marco-scoppetta** [comment] 2019-05-08 10:19
@lolski I agree we should have a proper migrator. I will close this as we know what the issue is:

in this PR https://github.com/graknlabs/grakn/pull/5114 we have moved to using Janus IDs to retrieve nodes instead of using the custom label that was in place before. When creating a new keyspace we actually update the `graknsystem` keyspace by adding a new `keyspace` attribute, but in 1.5.2 when trying to fetch attributes using IDs we get `null` because the `graknsystem` keyspace was built using the old way.

**Closed by marco-scoppetta** 2019-05-08 10:19 UTC
Labels: bug
