### ISSUE TITLE
insert schema to server database throws exception: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by gabywang5** [graknlabs/grakn#6267] opened 2021-03-26 09:54 UTC
## Description

Here is the big picture of my situation. I have Grakn server on my Linux and installed the client on Mac. (2 different computers). I serve the server on my Mac and run the client on Linux to communicate with the server.

Specifically, I run the script on Linux to insert a very simple schema. But the server shows the exception in pic-1, and the client shows the exception in pic-2.

pic-1
![image](https://user-images.githubusercontent.com/26650907/112603937-9992e180-8e50-11eb-81c5-90a51333ae81.png)

pic-2
![image](https://user-images.githubusercontent.com/26650907/112603607-31dc9680-8e50-11eb-8171-4c879459326f.png)

## Environment

1. OS (where Grakn server runs): Mac OS 10.15.5
2. Grakn version (and platform): Grakn Core 2.0.0-alpha-9(manually download)
3. Grakn client: client-python
4. Other environment details: grakn-client 2.0.0a7, grakn-protocol 2.0.0a9, graknprotocol 2.0.0a5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run 2.0.0-alpha-9 server on one computer(mac)
`./path-to-my-unzipped-grakn-folder/grakn serve`
2. Run the script in the terminal `insert_schema.py` on another computer (linux), the code is as follows(`xxx.xx.xx.xx` is my Mac ip address):
`python insert_schema.py`

content in `insert_schema.py`:
```python
from grakn.client import *

if __name__ == "__main__":
    uri = "xxx.xxx.xx.xx:1729"
    database = "biograkn_covid"

    with open("test_schema.gql", "r") as graql_file:
        schema = graql_file.read()

    with GraknClient.core(uri) as client:
        with client.session(database, SessionType.SCHEMA) as session:
            with session.transaction(TransactionType.WRITE) as write_transaction:
                write_transaction.query().define(schema)
                write_transaction.commit()
```
content in file `test_schema.gql`:
```
define

journal sub entity,
  owns journal-name;
```
3.  See the above error described in pic-1 and pic-2.

## Expected Output

Expect the script can normally insert the schema and no exception.

 
## Additional information

I originally run the script `migrate.py` in [https://github.com/graknlabs/biograkn-covid](url). To figure out which side of the problem is, I changed the script to the above one `insert_schema.py`, simply insert a one-line schema. The same exception still arose on the client-side.

So I reasonably blame the result on the server-side (Since my client script is simple and connects to the server normally).  I found this explanation [https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip](url) about the error `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer`. Since I am not familiar with the java thing, I still cannot solve it.

**Comment by haikalpribadi** [comment] 2021-03-26 18:13
Hi @gabywang5 the issue above is caused by the fact that the Java version on your machine is not Java 11 or higher. Can you try upgrading your Java version?

I apologise for the lack of useful error message. A better error message for this specific issue has been implemented in `master` and will be out with the next release.

**Comment by haikalpribadi** [comment] 2021-03-26 18:21
The solution (to inform the user of incompatible Java version) was implemented here: https://github.com/graknlabs/grakn/pull/6251

**Comment by haikalpribadi** [comment] 2021-03-26 18:22
I shall close this issue and mark it solved for now, @gabywang5 , but please let us know how it goes!

**Closed by haikalpribadi** 2021-03-26 18:22 UTC

**Comment by gabywang5** [comment] 2021-03-29 02:49
@haikalpribadi Dear friend, Thanks for your help. I upgrade my java from 8 to the latest 16 and the problem is gone!

Also, I appreciate your guide to the solution to inform the Java incompatible problem. It would be nice if Grakn provides a clear indication of where the problem is. 

Grakn is indeed a lovely community.
