### ISSUE TITLE
Analyse multithreading possibilities when reasoning

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3089] opened 2018-09-21 18:04 UTC
_This issue was originally posted by @kasper-piskorski  on 2017-05-19 17:13_.

As the reasoning is a granular operation, we can leverage multithreaded processing to traverse the resolution tree faster. Possible approaches: - spawning multiple single-threaded transactions - using single multi-threaded transaction (Janus provides these)

**Comment by marco-scoppetta** [comment] 2019-02-26 14:04
Closing this as we don't have hierarchy as we did in TP, so this is a duplicate of: https://github.com/graknlabs/grakn/issues/4216

**Closed by marco-scoppetta** 2019-02-26 14:04 UTC
Labels: feature, invalid
