### ISSUE TITLE
Graql: Some syntax errors appear to roll back a transaction

### ISSUE THREAD

**Issue by Tomen** [graknlabs/grakn#2624] opened 2018-02-07 19:42 UTC
Some syntax errors appear to roll back a transaction. This happens when I try to use `get` after `match` like in this example.

```
tomen@viech-ubuntu:~/Applications/grakn-dist-1.0.0$ ./graql console

Grakn  Copyright (C) 2016  Grakn Labs Limited 
This is free software, and you are welcome to redistribute it 
under certain conditions; type 'license' for details.
>>> insert $x isa profile;
$x id V69768 isa profile; 
>>> match $x isa profile; get;
$x id V69768 isa profile; 
>>> insert $x isa profile, has facebookId "yolo";
$x id V90176 isa profile; 
>>> match $x isa profile; get;
$x id V69768 isa profile; 
$x id V90176 isa profile; 
>>> yolo
syntax error at line 1: 
yolo
^
extraneous input 'yolo' expecting {<EOF>, 'compute', 'match', 'insert', 'define', 'undefine'}
>>> match $x isa profile; get;
$x id V69768 isa profile; 
$x id V90176 isa profile; 
>>> insert $x isa profile, has facebookId "foo";
$x id V57536 isa profile; 
>>> match $x isa profile;
syntax error at line 1: 
match $x isa profile;
                     ^
no viable alternative at input 'match $x isa profile;'
>>> match $x isa profile; get;
>>> 

```

**Comment by marco-scoppetta** [comment] 2019-02-28 12:19
Thanks @Tomen for reporting the issue. Closing this one as it's a duplicate of https://github.com/graknlabs/grakn/issues/4431

**Closed by marco-scoppetta** 2019-02-28 12:19 UTC
Labels: bug
