### ISSUE TITLE
graql.sh interactive mode only supports single-line queries

### ISSUE THREAD

**Issue by Phil-Young-Bose** [graknlabs/grakn#2171] opened 2017-10-03 20:24 UTC
The CLI (graql.sh in interactive mode, i.e. without -f) seems to only allow entering a query on one line. The example at https://grakn.ai/pages/documentation/get-started/setup-guide.html does show this ("match $x isa person, has identifier $n;"). However, one can paste a multiline query into the GUI, or run via "graql.sh -f <SCRIPT>". This caused me to suspect that the CLI error was due to a system configuration issue, which consumed some time to resolve. I could be wrong, but I don't see this limitation/gotcha in the docs or as an open issue.

**Comment by marco-scoppetta** [comment] 2019-02-28 13:33
Closing this as duplicate of https://github.com/graknlabs/grakn/issues/3871

**Closed by marco-scoppetta** 2019-02-28 13:33 UTC
