### ISSUE TITLE
Add an error message for reserved words

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2176] opened 2017-10-04 23:32 UTC
```
has label
        ^
no viable alternative at input 'has label'
```

**Comment by pouledodue** [comment] 2017-10-04 23:33
`your stuff contains reserved words` would be great

**Comment by marco-scoppetta** [comment] 2019-02-26 14:42
Closing, duplicate of https://github.com/graknlabs/grakn/issues/3763

**Closed by marco-scoppetta** 2019-02-26 14:42 UTC
Labels: invalid
