### ISSUE TITLE
Inconsistent Query Results

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#5355] opened 2019-08-06 02:54 UTC
## Description

Running the same query on an unchanged knowledge base results in inconsistent results. The results returned are correct but partial.

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04
2. Grakn version (and platform): Grakn Core 1.5.7

## Reproducible Steps

The reproducible steps involve using the software I've created. I'll be working on the functionality required to create external .gql scripts to reproduce. Just opening the ticket up now to start a discussion about the possible issue.

## Expected Output

I would expect Grakn to give the same answer to the same query when the underlying knowledge base hasn't changed no matter how many times it's executed.

## Actual Output

```
brandon@jimmy:/opt/grakn/grakn-core-all-linux-1.5.7$ ./grakn console -f /home/brandon/Desktop/test2.txt 
Loading: /home/brandon/Desktop/test2.txt
...
{$nToken id V86032 isa JavaSimpleNameArtifact; $functionArguments id V20656 isa JavaSingleVariableDeclarationArtifact; $ifStatement id V28824 isa JavaIfStatementArtifact; $whenIfTrue id V24736 isa JavaBlockArtifact; $n "n" isa token; $if_nToken id V106648 isa JavaSimpleNameArtifact; $twoLiteral id V90128 isa JavaNumberLiteralArtifact; $elseStatement id V45056 isa JavaBlockArtifact; $if_return id V69792 isa JavaReturnStatementArtifact; $lessThanCheck id V61664 isa JavaOperatorArtifact; $function_name "fib.fib(int)" isa name; $function id V8424 isa JavaMethodDeclarationArtifact; $arg id V82152 isa JavaSimpleNameArtifact; $ifConditional id V20640 isa JavaInfixExpressionArtifact; $functionBody id V28672 isa JavaBlockArtifact; $else_return id V40976472 isa JavaReturnStatementArtifact;}
{$nToken id V3051568 isa PythonNameArtifact; $functionArguments id V42610832 isa PythonArgumentsArtifact; $ifStatement id V3317960 isa PythonIfArtifact; $whenIfTrue id V42627216 isa PythonIfBodyArtifact; $n "n" isa token; $if_nToken id V3043376 isa PythonNameArtifact; $twoLiteral id V42676368 isa PythonNumArtifact; $elseStatement id V2928688 isa PythonIfOrelseArtifact; $if_return id V3039280 isa PythonReturnArtifact; $lessThanCheck id V1765456 isa PythonLtArtifact; $function_name "fib(n)" isa name; $function id V1699920 isa PythonFunctionDefArtifact; $arg id V3469512 isa PythonArgArtifact; $ifConditional id V1618112 isa PythonCompareArtifact; $functionBody id V1569008 isa PythonFunctionDefBodyArtifact; $else_return id V1622208 isa PythonReturnArtifact;}
Successful commit: test2.txt

brandon@jimmy:/opt/grakn/grakn-core-all-linux-1.5.7$ ./grakn console -f /home/brandon/Desktop/test2.txt 
Loading: /home/brandon/Desktop/test2.txt
...
{$nToken id V86032 isa JavaSimpleNameArtifact; $functionArguments id V20656 isa JavaSingleVariableDeclarationArtifact; $ifStatement id V28824 isa JavaIfStatementArtifact; $n "n" isa token; $whenIfTrue id V24736 isa JavaBlockArtifact; $if_nToken id V106648 isa JavaSimpleNameArtifact; $twoLiteral id V90128 isa JavaNumberLiteralArtifact; $elseStatement id V45056 isa JavaBlockArtifact; $if_return id V69792 isa JavaReturnStatementArtifact; $lessThanCheck id V61664 isa JavaOperatorArtifact; $function_name "fib.fib(int)" isa name; $function id V8424 isa JavaMethodDeclarationArtifact; $arg id V82152 isa JavaSimpleNameArtifact; $ifConditional id V20640 isa JavaInfixExpressionArtifact; $functionBody id V28672 isa JavaBlockArtifact; $else_return id V40976472 isa JavaReturnStatementArtifact;}
Successful commit: test2.txt
brandon@jimmy:/opt/grakn/grakn-core-all-linux-1.5.7$ 
```
 
## Additional information

Issue is visible when using Grakn Workbase too: https://www.youtube.com/watch?v=WtGMGn38o2Y

**Comment by kasper-piskorski** [comment] 2019-08-06 11:42
@BFergerson @flyingsilverfin has some export, import scripts we could potentially use to reproduce it

**Comment by flyingsilverfin** [comment] 2019-08-06 12:00
@BFergerson  we actually prefer to get the data by copying Grakn's `db` folder or sending a complete distribution :) the export/import isn't guaranted to be complete right now

**Comment by BFergerson** [comment] 2019-08-07 14:27
@flyingsilverfin, even easier. Here you go: [db.zip](https://github.com/graknlabs/grakn/files/3477460/db.zip)

And the query I was running:
```gql
match

#there is a function
$function isa SourceArtifact, has name $function_name;
($function) isa DECLARATION;
($function) isa FUNCTION;
not {
	($function) isa ARGUMENT;
};
not {
	($function) isa RETURN;
};
not {
	($function) isa INCOMPLETE;
};
not {
	($function) isa BODY;
};

#function has argument $n
(is_parent: $function, is_child: $functionArguments);
($functionArguments) isa FUNCTION;
($functionArguments) isa DECLARATION;
($functionArguments) isa ARGUMENT;
(is_parent: $functionArguments, is_child: $arg);
($arg) isa ARGUMENT;
($arg) isa NAME;
$arg has token $n;

#function has a body
(is_parent: $function, is_child: $functionBody);
($functionBody) isa BODY;

#function body contains an if statement
(is_parent: $functionBody, is_child: $ifStatement);
($ifStatement) isa IF;

#if statement has conditional ($n < 2)
(is_parent: $ifStatement, is_child: $ifConditional);
$nToken has token $n; (is_parent: $ifConditional, is_child: $nToken);
$lessThanCheck has token "<"; (is_parent: $ifConditional, is_child: $lessThanCheck);
$twoLiteral has numberValue 2; (is_parent: $ifConditional, is_child: $twoLiteral);

#if statement returns $n
(is_parent: $ifStatement, is_child: $whenIfTrue);
($whenIfTrue) isa THEN;
($if_return) isa RETURN; (is_parent: $whenIfTrue, is_child: $if_return);
$if_nToken has token $n; (is_parent: $if_return, is_child: $if_nToken);

#if statement has else statement
(is_parent: $ifStatement, is_child: $elseStatement);
($elseStatement) isa ELSE;

#else statement returns $f($n - 1) + $f($n - 2)
(is_parent: $elseStatement, is_child: $else_return);
($else_return) isa RETURN;

get;
```

**Comment by kasper-piskorski** [comment] 2019-08-15 11:07
@BFergerson 
Just an update: the fix (#5373) is currently waiting to be merged.

Also going through you data we noticed two things:
- The roles `is_parent` and `is_child` have 415 subroles. Is there any particular reason for this massive role hierarchy? Is there a particular benefit of that?
- The unary capitalised relations: `DECLARATION`, `FUNCTION`, etc. What's the motiviation of defining them?  Is it to simulate multitype instances?

**Closed** 2019-08-15 11:08 UTC
Labels: bug, in progress

**Comment by BFergerson** [comment] 2019-08-15 13:29
@kasper-piskorski, thanks for resolving this issue for me. I've been working on Graql export functionality so future bugs I can give much less schema/data to reproduce. I imagine it was pretty difficult with the full schema.

With that being said, I've never had any external input on the schema I've been designing. It was my hope that that queries would benefit from the massive role hierarchy. There are relationships like `is_parent/is_child` and it has children like `has_argument/is_argument`. It was my hope that if I was looking only for `has_argument/is_argument` that Grakn would be able to ignore all the other roles and only look for that one. If I wanted to not care about what type of relationship two nodes share then I can default to the `is_parent/is_child` relationship. The ability to build complex schemas is why I choose a knowledge graph over a relational database. Modeling this in a relational database would have meant 415 join tables. Do I not get any speed increases by creating a role hierarchy? For example, let's say I have 100 `has_argument/is_argument` and 1000 `has_caller/is_callee`. Wouldn't queries on the `has_caller/is_callee` potentially take longer and ultimately not affect the speed of the `has_argument/is_argument`? Of course, querying by `is_parent/is_child` would take longer than both combined.

As for the `DECLARATION`, `FUNCTION`, etc roles I think you understood their purpose. They are the semantic roles source code can play and one particular AST node can be playing several roles at a time.

**Comment by kasper-piskorski** [comment] 2019-08-15 14:32
You are generally right. If you query for specialised roles the search space will be constrained downstream (to the specified roles and their subroles). I am not saying it's right or wrong, just wanted to get an understanding of the motivation in this particular case. 

That being said, with extensive hierarchies of roles present, currently there is a performance hit if you query for the base roles. It's due to the fact how we traverse them at the moment - we use a gremlin `.within` step to go through the possible roles. We are currently planning to optimise this. Just to let know you.
