### ISSUE TITLE
compute count; and match $x; aggregate count; give different results

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4072] opened 2018-09-22 00:43 UTC
_This issue was originally posted by @jmsfltchr  on 2018-07-13 19:41_.

Often big differences between`compute count` and `match $x; aggregate count;` For instance in my current dataset `compute count` = 316 `match $x; aggregate count;` = 828

**Comment by marco-scoppetta** [comment] 2019-04-15 11:59
closing as duplicate of https://github.com/graknlabs/grakn/issues/3962

**Closed by marco-scoppetta** 2019-04-15 11:59 UTC
Labels: bug, invalid
