### ISSUE TITLE
Reduce `grakn-core` dependencies

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3824] opened 2018-09-21 23:48 UTC
_This issue was originally posted by @haikalpribadi  on 2018-01-10 12:16_.

`grakn-core` has lots of dependencies that it may not need, such as:
redisq
tinkerpop
mjson
and many more

**Comment by marco-scoppetta** [comment] 2019-04-05 15:05
Closing as duplicate of https://github.com/graknlabs/grakn/issues/4321

**Closed by marco-scoppetta** 2019-04-05 15:05 UTC
Labels: feature
